apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: green-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shannkz/green-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true  # No changes to the cluster via kubectl, only Git
      prune: true  # delete the old resource